// This file is generated by Slice Machine. Update with care!

import SectionAbout from './SectionAbout';
import SectionAdvantage from './SectionAdvantage';
import SectionCta from './SectionCta';
import SectionEveryone from './SectionEveryone';
import SectionHeader from './SectionHeader';
import SectionHelp from './SectionHelp';
import SectionHeroHome from './SectionHeroHome';
import SectionResults from './SectionResults';

export {
	SectionAbout,
	SectionAdvantage,
	SectionCta,
	SectionEveryone,
	SectionHeader,
	SectionHelp,
	SectionHeroHome,
	SectionResults,
};

export const components = {
	section_about: SectionAbout,
	section_advantage: SectionAdvantage,
	section_cta: SectionCta,
	section_everyone: SectionEveryone,
	section_header: SectionHeader,
	section_help: SectionHelp,
	section_hero_home: SectionHeroHome,
	section_results: SectionResults,
};
