// This file is generated by Slice Machine. Update with care!

import GeneralCard from './GeneralCard';
import SectionAbout from './SectionAbout';
import SectionAdvantage from './SectionAdvantage';
import SectionCta from './SectionCta';
import SectionEveryone from './SectionEveryone';
import SectionForm from './SectionForm';
import SectionHelp from './SectionHelp';
import SectionHeroHome from './SectionHeroHome';
import SectionHeroPage from './SectionHeroPage';
import SectionMaxResults from './SectionMaxResults';
import SectionPolicyAndTerms from './SectionPolicyAndTerms';
import SectionResults from './SectionResults';

export {
	GeneralCard,
	SectionAbout,
	SectionAdvantage,
	SectionCta,
	SectionEveryone,
	SectionForm,
	SectionHelp,
	SectionHeroHome,
	SectionHeroPage,
	SectionMaxResults,
	SectionPolicyAndTerms,
	SectionResults,
};

export const components = {
	general_card: GeneralCard,
	section_about: SectionAbout,
	section_advantage: SectionAdvantage,
	section_cta: SectionCta,
	section_everyone: SectionEveryone,
	section_form: SectionForm,
	section_help: SectionHelp,
	section_hero_home: SectionHeroHome,
	section_hero_page: SectionHeroPage,
	section_max_results: SectionMaxResults,
	section_policy_and_terms: SectionPolicyAndTerms,
	section_results: SectionResults,
};
